# Generated by Django 5.2.8 on 2025-12-01 07:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('main_content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('feature', 8), ('cta', 10)], blank=True, block_lookup={0: ('cms_app.blocks.HeadingBlock', (), {}), 1: ('cms_app.blocks.ParagraphBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('icon', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('text', 5), ('button_text', 5), ('button_link', 9)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
